name: "Conventional Commits"
description: "Ensures that all commit messages are following the conventional-commits standard."
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: false
  allowed-commit-types:
    description: 'Specify a comma separated list of allowed commit types'
    default: 'feat,fix,docs,style,refactor,test,build,perf,ci,chore,revert,merge,wip'
    required: false

runs:
  using: node16
  main: dist/main/index.js
